name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - build.sh
      - .github/workflows/nightly.yaml

jobs:

  nightly:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run build script
      run: |
        chmod +x ./build.sh
        ./build.sh nightly

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nightly-artifacts
        path: ~/hyprsource/artifact/
